import Head from "next/head";
import Layout from "../components/layout";
import Hero from "../components/Home/hero";
import Animation from "../components/Home/animation";

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>Hello World</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* 메인 내용 부분 */}
            <section className="flex min-h-screen items-center justify-center text-gray-600 body-font">
                <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                    <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
                        <Hero />
                    </div>
                    <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                        <Animation />
                    </div>
                </div>
            </section>
        </Layout>
    );
}
